---
title: "HW 2"
author: "Mateo Forero"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding = encoding,
  output_file = file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

##


```{r}
#Importing Library and dataset
library(tidyverse)
library(plotly)
raw_data <- read.csv("Country_GDP.csv")
```
## Filter, extract, and clean relevant data
```{r}
c_code <- c("USA","EUU","CHN","JPN","CAN","BRA")
filt_data <- filter(raw_data,Country.Code %in% c_code)
colnames(filt_data) <- col_nam <- c("Country",
                                        "Country_Code",seq(2001,2020))

plot_data <- data.frame(t(filt_data[,3:22]))
colnames(plot_data) <- filt_data$Country_Code


#GDP Per Billion dollars
plot_data <- plot_data/1000000000
head(plot_data)
```

## Creating the plot
```{r, fig.width=9.5}
fig <- plot_ly(plot_data, type = 'scatter', mode = 'lines') %>%
  add_trace(x = seq(2001,2020), y = ~BRA, name = 'Brazil') %>%
  add_trace(x = seq(2001,2020), y = ~CAN, name = 'Canada') %>%
  add_trace(x = seq(2001,2020), y = ~CHN, name = 'China') %>%
  add_trace(x = seq(2001,2020), y = ~EUU, name = 'EU') %>%
  add_trace(x = seq(2001,2020), y = ~JPN, name = 'Japan') %>%
  add_trace(x = seq(2001,2020), y = ~USA, name = 'USA') %>%
  layout(title = "Major Countries GDP",
         legend = list(title=list(text='Countries'),x=-0.3,y=0), 
         xaxis = list(title = 'Date',
                      rangeslider = list(visible = T)),
         yaxis = list(title = 'GDP [$Billions]'),
         plot_bgcolor='#e5ecf6',
         
         updatemenus = list(
           list(
             buttons = list(
               list(method = 'restyle',
                    args = list('visible',list(TRUE,TRUE,TRUE,TRUE,TRUE,TRUE)),
                    label = "All"),
               
               list(method = 'restyle',
                    args = list('visible',list(TRUE,FALSE,FALSE,TRUE,TRUE,FALSE)),
                    label = "Super Powers"),
               
               list(method = 'restyle',
                    args = list('visible',list(TRUE,FALSE,TRUE,FALSE,FALSE,FALSE)),
                    label = "North America")))
           ))

fig
```



